name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Info
        id: info
        run: |
          echo "RELEASE_NAME=task.json-web-$(basename $GITHUB_REF)" >> $GITHUB_ENV

      - name: Build task.json-web
        run: |
          npm ci
          npm run build

      - name: Create archive 
        run: |
          cd build
          zip -9 -r ../$RELEASE_NAME.zip .

      - name: Upload to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ steps.info.outputs.RELEASE_NAME }}.zip
          tag: ${{ github.ref }}
          overwrite: true

